/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Chef;
import Model.Contact;
import Model.Recipe;
import java.awt.Image;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static javax.swing.text.html.HTML.Tag.OPTION;

/**
 *
 * @author Chilukuri
 */
public class foodblog_backup extends javax.swing.JFrame {

    /**
     * Creates new form foodblog
     */
    
    private Chef chef;
    
    public foodblog_backup() {
        initComponents();
        
        this.chef = new Chef();
        chef.setContact(new Contact())  ;
        chef.setRecipe(new Recipe());
    }
                                   
    
    private void display(){
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        recipeTitleField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        recipeDescField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        servingsSizeField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        numIngredientsField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        categoryField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        isGlutenFreeField = new javax.swing.JCheckBox();
        uploadRecipeImageButton = new javax.swing.JButton();
        recipeImageLabel = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        difficultyLabel = new javax.swing.JLabel();
        difficultyField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(450);
        jSplitPane1.setDividerSize(10);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setText("First Name");

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Last Name");

        jLabel4.setText("Username");

        jLabel5.setText("Recipe Title");

        recipeTitleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeTitleFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Recipe Description");

        jLabel7.setText("Num.of.Servings");

        jLabel8.setText("Num.Of.Ingredients");

        jLabel9.setText("Category");

        jLabel10.setText("Is Gluten Free");

        isGlutenFreeField.setText("jCheckBox1");

        uploadRecipeImageButton.setText("Upload Recipe Image");
        uploadRecipeImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadRecipeImageButtonActionPerformed(evt);
            }
        });

        save.setText("Save Recipe");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel12.setText("Phone");

        jLabel13.setText("Email");

        edit.setText("Edit Recipe");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        clear.setText("Clear Recipe");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        difficultyLabel.setText("Difficulty");

        difficultyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultyFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(uploadRecipeImageButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(recipeImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userNameField)
                                    .addComponent(firstNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lastNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(difficultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(isGlutenFreeField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(servingsSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numIngredientsField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(recipeTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(379, 379, 379)
                                        .addComponent(clear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(edit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(save)))
                                .addContainerGap(35, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(difficultyField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(recipeDescField, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(firstNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(recipeDescField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(recipeTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servingsSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numIngredientsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clear)
                        .addComponent(edit)
                        .addComponent(save))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(difficultyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(difficultyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(isGlutenFreeField))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uploadRecipeImageButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(recipeImageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );

        jSplitPane1.setTopComponent(jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 878, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recipeTitleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeTitleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recipeTitleFieldActionPerformed

    private void uploadRecipeImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadRecipeImageButtonActionPerformed
        JFileChooser uploadRecipeImage = new JFileChooser();

        FileNameExtensionFilter file_ext_filter = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg"); 
        uploadRecipeImage.addChoosableFileFilter(file_ext_filter);
        int showOpenDialogue = uploadRecipeImage.showOpenDialog (null);
        
        if(showOpenDialogue == JFileChooser.APPROVE_OPTION)
        {
            File selectedImageFile = uploadRecipeImage.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            ImageIcon ii = new ImageIcon(selectedImagePath);
            Image image = ii.getImage().getScaledInstance(recipeImageLabel.getWidth(), recipeImageLabel.getHeight(), Image.SCALE_SMOOTH);
            recipeImageLabel.setIcon(new ImageIcon (image));
        }
    }//GEN-LAST:event_uploadRecipeImageButtonActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();
        String userName = userNameField.getText();
        String phone = phoneField.getText();
        String email = emailField.getText();
        String recipeTitle = recipeTitleField.getText();
        String description = recipeDescField.getText();
        String servingsSize = servingsSizeField.getText();
        String isGlutenFree = isGlutenFreeField.getText();
        String numOfIngredients = numIngredientsField.getText();
        String category = categoryField.getText();
        String difficulty = difficultyField.getText();
        
        //null checks - checking with isBlank() to avoid whitespaces
        if(firstName.isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter the FirstName");
        }
        else if(lastName.isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter the LastName");
        }
        else if(userName.isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter a valid username");
        }
        else if(email.isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter a email");
        }
        else if(phone.isBlank()){
             JOptionPane.showMessageDialog(null, "Please enter a phone number");
        }
        else if(recipeTitle.isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter a recipe title");
        }
        else if(servingsSize.isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter a servings size");
        }
        else if(difficulty.isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter the difficulty level");
        }
        else if(numOfIngredients.isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter the number of ingredients");
        }
        else if(category.isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter a category");
        }
        else if(description.isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter a recipe description");
        }
        else if(recipeImageLabel.getIcon() == null){
            JOptionPane.showMessageDialog(null, "Please upload a recipe image");
        }
        
        //additional validations
        if(!ValidateNames(firstName)){
            JOptionPane.showMessageDialog(null, "Please enter a valid FirstName");
        }
        else if(!ValidateNames(lastName)){
            JOptionPane.showMessageDialog(null, "Please enter a valid LastName");
        }
        else if(!ValidateUserName(userName)){
            JOptionPane.showMessageDialog(null, "Please enter a valid username");
        }
        else if(!ValidateEmail(email)){
            JOptionPane.showMessageDialog(null, "Please enter a valid email");
        }
        else if(!ValidatePhone(phone)){
             JOptionPane.showMessageDialog(null, "Please enter a valid phone number");
        }
        else if(!ValidateNames(recipeTitle)){
            JOptionPane.showMessageDialog(null, "Please enter a valid recipe title");
        }
        else if(!ValidateIntegerFields(servingsSize)){
            JOptionPane.showMessageDialog(null, "Please enter a valid servings size");
        }
        else if(!ValidateDifficulty(difficulty)){
            JOptionPane.showMessageDialog(null, "Please enter a valid difficulty level");
        }
        else if(!ValidateIntegerFields(numOfIngredients)){
            JOptionPane.showMessageDialog(null, "Please enter a valid number of ingredients");
        }
        else if(!ValidateNames(category)){
            JOptionPane.showMessageDialog(null, "Please enter a valid category");
        }
        else if(!ValidateNames(description)){
            JOptionPane.showMessageDialog(null, "Please enter a valid recipe description");
        }
        else{
            chef.getContact().setEmail(email);
            chef.getContact().setPhone(phone);

            chef.getRecipe().setRecipeTitle(recipeTitle);
            chef.getRecipe().setDescription(description);
            chef.getRecipe().setCategory(category);
            chef.getRecipe().setNumberOfIngredients(Integer.parseInt(numOfIngredients));
            chef.getRecipe().setNumberOfServings(Integer.parseInt(servingsSize));
            chef.getRecipe().setIsGlutenFree(Boolean.getBoolean(isGlutenFree));
            chef.getRecipe().setDifficulty(Float.parseFloat(difficulty));
            chef.getRecipe().setRecipePicture(recipeImageLabel.getIcon());

            this.chef.setFirstName(firstName);
            this.chef.setLastName(lastName);
            this.chef.setUserName(userName);
            disableFields();
        }   
    }//GEN-LAST:event_saveActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        enableFields();
    }//GEN-LAST:event_editActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       clearFields();
       enableFields();
       this.chef = new Chef(); // reset saved object
    }//GEN-LAST:event_clearActionPerformed

    private void difficultyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_difficultyFieldActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foodblog_backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foodblog_backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foodblog_backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foodblog_backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foodblog_backup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoryField;
    private javax.swing.JButton clear;
    private javax.swing.JTextField difficultyField;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JButton edit;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JCheckBox isGlutenFreeField;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField numIngredientsField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField recipeDescField;
    private javax.swing.JLabel recipeImageLabel;
    private javax.swing.JTextField recipeTitleField;
    private javax.swing.JButton save;
    private javax.swing.JTextField servingsSizeField;
    private javax.swing.JButton uploadRecipeImageButton;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables

    private void disableFields() {
        firstNameField.setEnabled(false);
        lastNameField.setEnabled(false);
        userNameField.setEnabled(false);
        phoneField.setEnabled(false);
        emailField.setEnabled(false);
        recipeTitleField.setEnabled(false);
        recipeDescField.setEnabled(false);
        servingsSizeField.setEnabled(false);
        isGlutenFreeField.setEnabled(false);
        numIngredientsField.setEnabled(false);
        categoryField.setEnabled(false);
        uploadRecipeImageButton.setEnabled(false);
        difficultyField.setEnabled(false);
    }
    
    private void enableFields() {
        firstNameField.setEnabled(true);
        lastNameField.setEnabled(true);
        userNameField.setEnabled(true);
        phoneField.setEnabled(true);
        emailField.setEnabled(true);
        recipeTitleField.setEnabled(true);
        recipeDescField.setEnabled(true);
        servingsSizeField.setEnabled(true);
        isGlutenFreeField.setEnabled(true);
        numIngredientsField.setEnabled(true);
        categoryField.setEnabled(true);
        uploadRecipeImageButton.setEnabled(true);
        difficultyField.setEnabled(true);
    }
    
    private void clearFields() {
        firstNameField.setText("");
        lastNameField.setText("");
        userNameField.setText("");
        phoneField.setText("");
        emailField.setText("");
        recipeTitleField.setText("");
        recipeDescField.setText("");
        servingsSizeField.setText("");
        isGlutenFreeField.setSelected(false);
        numIngredientsField.setText("");
        categoryField.setText("");
        recipeImageLabel.setIcon(null);
        difficultyField.setText("");
    }
    
    private boolean ValidateNames(String name)
    {
        String pattern = "^[a-zA-Z\\s]*$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(name);
        return match.matches();
    }
    
    private boolean ValidateUserName(String userName)
    {
        String pattern = "^[a-zA-Z0-9]+([._]?[a-zA-Z0-9]+)*$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(userName);
        return match.matches();
    }
    
    private boolean ValidateIntegerFields(String fieldValue)
    {
        String pattern = "^[1-9]{0,2}";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(fieldValue);
        return match.matches();
    }
    
    private boolean ValidateEmail(String email)
    {
        String pattern ="[a-z0-9]+@[a-z]+\\.[a-z]{2,3}";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(email);
        return match.matches();
    }
    
    private boolean ValidatePhone(String phone)
    {
        String pattern = "^[0-9]{0,10}";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(phone);
        return match.matches();
    }
    
    private boolean ValidateDifficulty(String difficulty)
    {
        String pattern = "[+-]?([0-9]*[.])?[0-9]+";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(difficulty);
        return match.matches();
        
    }
            
 }
