/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package UI.BranchManagerPanels;

import Business.Branch;
import Services.RentalRequest;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chilukuri
 */
public class BranchRentalRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LibRentalRequestsJPanel
     */
    private Branch branch;
    DefaultTableModel renRequestsTableModel;
    
    public BranchRentalRequestsJPanel(Branch branch) {
        initComponents();
        this.branch = branch;
        this.renRequestsTableModel = (DefaultTableModel) bmRenRequestsJTable.getModel();
        
        displayRentalRequests();
        displayTotalRevenue();
    }
    
    private void displayTotalRevenue(){
        ArrayList<RentalRequest> rr = this.branch.getLibrary().getRentals().getOrderlist();
        double revenue = 0.0;
        for(RentalRequest r: rr) 
        {
            if(r.getStatus().toLowerCase().equals("rejected"))
            {
                continue;
            }
            else
            {
                revenue = revenue + r.getPrice();
            }
        }
        
        displayRevenueLabel.setText(String.valueOf(revenue));
    }
    
    private void displayRentalRequests() {
        ArrayList<RentalRequest> rr = this.branch.getLibrary().getRentals().getOrderlist();
        if(rr.size() >= 0) {
            renRequestsTableModel.setRowCount(0);
            for(RentalRequest r: rr) {
                Object row[] = new Object[7];
                row[0] = r.getOrderId();
                row[1] = r.getMaterialId();
                row[2] = r.getCustomer().getPersonID();
                row[3] = r.getBranch().getBranchId();
                row[4] = r.getPrice();
                row[5] = r.getStatus();
                row[6] = r.getDuration();
                renRequestsTableModel.addRow(row);           
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bmRenRequestsJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        displayRevenueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 255));

        bmRenRequestsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order Id", "Material ID", "Customer Id", "Branch Id", "Price", "Status", "Duration"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bmRenRequestsJTable);

        jLabel1.setText("Total Revenue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(displayRevenueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(displayRevenueLabel))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bmRenRequestsJTable;
    private javax.swing.JLabel displayRevenueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
