/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.BranchManagerPanels;

import Business.Branch;
import Business.Business;
import Business.Library;
import Business.UserAccount;
import Customer.Employee;
import Material.Book;
import Material.Magazine;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chilukuri
 */
public class MagazinesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MagazinesJPanel
     */
    private Branch branch;
    DefaultTableModel magsTableModel;
    
    public MagazinesJPanel(Branch branch) {
        initComponents();
        this.branch = branch;
        this.magsTableModel = (DefaultTableModel) bmMagsJTable.getModel();
        
        displayMagazines();
    }
    
    private void displayMagazines() {
        ArrayList<Magazine> mags = this.branch.getLibrary().getMagazines().getMagazinesList();
        
        if(mags.size() >= 0) {
            magsTableModel.setRowCount(0);
            for(Magazine b: mags) {
                Object row[] = new Object[6];
                row[0] = b.getSerialNumber();
                row[1] = b.getName();
                row[2] = b.getRegisteredDate().toString();
                row[3] = b.getIsAvailable();
                row[4] = b.getCompanyName();
                row[5] = b.getIssueType();
                magsTableModel.addRow(row);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bmMagsJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 51, 204));

        bmMagsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "S.No", "Name", "Registred Date", "Is Available", "Company", "Issue Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bmMagsJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bmMagsJTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
