/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.LibrarianPanels;

import Business.Branch;
import Business.Library;
import Material.Author;
import Material.Book;
import Material.Genre;
import Material.Magazine;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chilukuri
 */
public class MagazinesJPanel extends javax.swing.JPanel {

    private Branch branch;
    DefaultTableModel magsTableModel;
    
    public MagazinesJPanel(Branch branch) {
        initComponents();
        this.branch = branch;
        this.magsTableModel = (DefaultTableModel) libMagazinesJTable.getModel();
        
        displayMagazines();
    }
    
    private void displayMagazines() {
        ArrayList<Magazine> mags = this.branch.getLibrary().getMagazines().getMagazinesList();
        
        if(mags.size() >= 0) {
            magsTableModel.setRowCount(0);
            for(Magazine b: mags) {
                Object row[] = new Object[6];
                row[0] = b.getSerialNumber();
                row[1] = b.getName();
                row[2] = b.getRegisteredDate().toString();
                row[3] = b.getIsAvailable();
                row[4] = b.getCompanyName();
                row[5] = b.getIssueType();
                magsTableModel.addRow(row);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        magSNoTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        libMagNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        libMagIsAvailable = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        libMagCmpNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        libMagIssueTypeTextField = new javax.swing.JTextField();
        addMagazineBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        libMagazinesJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 0, 153));

        jLabel1.setText("Serial Number");

        jLabel2.setText("Name");

        libMagNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libMagNameTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("isAvailable");

        jLabel5.setText("Company Name");

        jLabel6.setText("Issue Type");

        addMagazineBtn.setText("Add Magazine");
        addMagazineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMagazineBtnActionPerformed(evt);
            }
        });

        libMagazinesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "S.No", "Name", "Registred Date", "Is Available", "Company", "Issue Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(libMagazinesJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(addMagazineBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(magSNoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(libMagNameTextField)
                                    .addComponent(libMagIsAvailable))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(libMagCmpNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(libMagIssueTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(magSNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(libMagCmpNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(libMagNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(libMagIssueTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(libMagIsAvailable))
                .addGap(27, 27, 27)
                .addComponent(addMagazineBtn)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addMagazineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMagazineBtnActionPerformed
        String sNo = magSNoTextField.getText();
        String magName = libMagNameTextField.getText();
        Date currentDate = new Date();
        String regDate = currentDate.toString();
        boolean isAvailable = libMagIsAvailable.isSelected();
        String companyName = libMagCmpNameTextField.getText();
        String issueType = libMagIssueTypeTextField.getText();
        
        if (this.branch.getLibrary().getMagazines().checkIfMagazineExists(sNo))
        {
            JOptionPane.showMessageDialog(null, "Magazine already exists!");
        }
        else{
        
            Magazine m = new Magazine(sNo, magName, currentDate,
                    isAvailable,companyName, issueType);
            
            Library lib = branch.getLibrary();
            lib.getMagazines().addMagazine(m);
            
            displayMagazines();

            magSNoTextField.setText("");
            libMagNameTextField.setText("");
            libMagCmpNameTextField.setText("");
            libMagIssueTypeTextField.setText("");    
        }
    }//GEN-LAST:event_addMagazineBtnActionPerformed

    private void libMagNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libMagNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libMagNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMagazineBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField libMagCmpNameTextField;
    private javax.swing.JCheckBox libMagIsAvailable;
    private javax.swing.JTextField libMagIssueTypeTextField;
    private javax.swing.JTextField libMagNameTextField;
    private javax.swing.JTable libMagazinesJTable;
    private javax.swing.JTextField magSNoTextField;
    // End of variables declaration//GEN-END:variables
}
