/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author Prasad
 */
public class InsurancePlansJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsurancePlansJPanel
     */
    public InsurancePlansJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        planIdLabel = new javax.swing.JLabel();
        planNameLabel = new javax.swing.JLabel();
        costPerMonthLabel = new javax.swing.JLabel();
        costPerYearLabel = new javax.swing.JLabel();
        planIdTextField = new javax.swing.JTextField();
        planNameTextField = new javax.swing.JTextField();
        costPerMonthTextField = new javax.swing.JTextField();
        costPerYearTextField = new javax.swing.JTextField();
        savePlanButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        insurancePlansJTable = new javax.swing.JTable();
        viewPlanDetailsButton = new javax.swing.JButton();
        deleteInsurancePlanButton = new javax.swing.JButton();

        planIdLabel.setText("Plan ID");

        planNameLabel.setText("Plan Name");

        costPerMonthLabel.setText("Cost Per Month");

        costPerYearLabel.setText("Cost Per Year");

        savePlanButton.setText("Save Plan");

        insurancePlansJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Plan ID", "Plan Name", "Cost Per Month", "Cost Per Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(insurancePlansJTable);

        viewPlanDetailsButton.setText("View Plan Details");
        viewPlanDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPlanDetailsButtonActionPerformed(evt);
            }
        });

        deleteInsurancePlanButton.setText("Delete Plan");
        deleteInsurancePlanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInsurancePlanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(planIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(planNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(costPerMonthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(costPerYearLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(planIdTextField)
                            .addComponent(planNameTextField)
                            .addComponent(costPerMonthTextField)
                            .addComponent(costPerYearTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(savePlanButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(deleteInsurancePlanButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewPlanDetailsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(planIdLabel)
                            .addComponent(planIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(planNameLabel)
                            .addComponent(planNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(costPerMonthLabel)
                            .addComponent(costPerMonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(costPerYearLabel)
                            .addComponent(costPerYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(savePlanButton)))
                .addGap(33, 33, 33)
                .addComponent(viewPlanDetailsButton)
                .addGap(28, 28, 28)
                .addComponent(deleteInsurancePlanButton)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewPlanDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPlanDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPlanDetailsButtonActionPerformed

    private void deleteInsurancePlanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInsurancePlanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteInsurancePlanButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel costPerMonthLabel;
    private javax.swing.JTextField costPerMonthTextField;
    private javax.swing.JLabel costPerYearLabel;
    private javax.swing.JTextField costPerYearTextField;
    private javax.swing.JButton deleteInsurancePlanButton;
    private javax.swing.JTable insurancePlansJTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel planIdLabel;
    private javax.swing.JTextField planIdTextField;
    private javax.swing.JLabel planNameLabel;
    private javax.swing.JTextField planNameTextField;
    private javax.swing.JButton savePlanButton;
    private javax.swing.JButton viewPlanDetailsButton;
    // End of variables declaration//GEN-END:variables
}
