/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Application;
import Business.ApplicationDirectory;
import Business.Catalog;
import Business.InsurancePlan;
import Business.Vaccine;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Prasad
 */
public class SearchApplicationsJPanel extends javax.swing.JPanel {

    private Catalog catalog;
    DefaultTableModel searchResultsTableModel;
    
    public SearchApplicationsJPanel(Catalog catalog) {
        initComponents();
        
        this.catalog = catalog;
        this.searchResultsTableModel = (DefaultTableModel) searchResultsTable.getModel(); 
    }
    
    public void displaySearchResults(ArrayList<Application> applications) {
        if(applications.size() >= 0) {
            searchResultsTableModel.setRowCount(0);
            for(Application app: applications) {
                Object row[] = new Object[6];
                row[0] = app.getApplicationId();
                row[1] = app.getApplicantFirstName();
                row[2] = app.getApplicantLastName();
                row[3] = app.getPetName();
                row[4] = app.getPetInsurancePlan().getPlanId();
                row[5] = app.getApplicationDate().toString();
                searchResultsTableModel.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultsTable = new javax.swing.JTable();
        searchAppIdTextField = new javax.swing.JTextField();
        searchAppIdButton = new javax.swing.JButton();
        searchFirstNameTextField = new javax.swing.JTextField();
        searchFirstNameButton = new javax.swing.JButton();
        clearResultsButton = new javax.swing.JButton();

        searchResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ApplicantID", "FirstName", "LastName", "Pet Name", "Insurance Plan", "Application Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(searchResultsTable);

        searchAppIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAppIdTextFieldActionPerformed(evt);
            }
        });

        searchAppIdButton.setText("Search using AppId");
        searchAppIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAppIdButtonActionPerformed(evt);
            }
        });

        searchFirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFirstNameTextFieldActionPerformed(evt);
            }
        });

        searchFirstNameButton.setText("Search using FirstName");
        searchFirstNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFirstNameButtonActionPerformed(evt);
            }
        });

        clearResultsButton.setText("Clear Results");
        clearResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearResultsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(searchFirstNameButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchAppIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(searchAppIdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearResultsButton))
                .addContainerGap(468, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchAppIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchAppIdButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchFirstNameButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(clearResultsButton)
                .addContainerGap(360, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchAppIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAppIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchAppIdTextFieldActionPerformed

    private void searchFirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFirstNameTextFieldActionPerformed

    private void searchAppIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAppIdButtonActionPerformed
        String searchAppIdValue = searchAppIdTextField.getText();
        ArrayList<Application> searchResults = new ArrayList<Application>();
        searchResults.add(this.catalog.getAppDirectory().findApplicationById(searchAppIdValue));
        displaySearchResults(searchResults);
    }//GEN-LAST:event_searchAppIdButtonActionPerformed

    private void searchFirstNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFirstNameButtonActionPerformed
        String searchAppFName = searchFirstNameTextField.getText();
        ArrayList<Application> searchResults = this.catalog.getAppDirectory().findApplicationByFirstName(searchAppFName);
        displaySearchResults(searchResults);
    }//GEN-LAST:event_searchFirstNameButtonActionPerformed

    private void clearResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearResultsButtonActionPerformed
        ArrayList<Application> searchResults = new ArrayList<Application>();
        displaySearchResults(searchResults);
    }//GEN-LAST:event_clearResultsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearResultsButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchAppIdButton;
    private javax.swing.JTextField searchAppIdTextField;
    private javax.swing.JButton searchFirstNameButton;
    private javax.swing.JTextField searchFirstNameTextField;
    private javax.swing.JTable searchResultsTable;
    // End of variables declaration//GEN-END:variables
}
