/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminPanels;

import Business.Branch;
import Business.BranchDirectory;
import Business.Business;
import Business.Library;
import Business.LibraryDirectory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chilukuri
 */
public class BranchesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BranchesJPanel
     */
    
    private Business business;
    DefaultTableModel branchesTableModel;
    
    public BranchesJPanel(Business business) {
        initComponents();
        this.business = business;
        this.branchesTableModel = (DefaultTableModel) branchesJTable.getModel();
        
        displayBranches();
        
        //populateDropdowns();
    }
    
    private void displayBranches() {
        ArrayList<Branch> branches = this.business.getBranches().getBranchesList();
        if(branches.size() >= 0) {
            branchesTableModel.setRowCount(0);
            for(Branch b: branches) {
                Object row[] = new Object[3];
                row[0] = b.getBranchId();
                row[1] = b.getName();
                row[2] = b.getLibrary().getBuildingNumber();
                branchesTableModel.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        branchNameLabel = new javax.swing.JLabel();
        branchNameTextField = new javax.swing.JTextField();
        addBranchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buildingNumLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        branchesJTable = new javax.swing.JTable();
        deleteBranchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        libBuildingNumTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 153, 255));

        branchNameLabel.setText("Branch Name");

        addBranchBtn.setText("Add Branch");
        addBranchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBranchBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Add a new Branch");

        buildingNumLabel.setText("Building #");

        branchesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Branch ID", "Branch Name", "Library Building #"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(branchesJTable);

        deleteBranchButton.setText("Delete Branch");
        deleteBranchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBranchButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Available Branches");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(branchNameLabel)
                            .addComponent(buildingNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(branchNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(libBuildingNumTextField))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addBranchBtn)
                        .addGap(110, 110, 110)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBranchButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(branchNameLabel)
                            .addComponent(branchNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(libBuildingNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buildingNumLabel))
                        .addGap(29, 29, 29)
                        .addComponent(addBranchBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(deleteBranchButton)
                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBranchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBranchBtnActionPerformed
        String branchName = branchNameTextField.getText();
        int libraryBuilding = Integer.valueOf(libBuildingNumTextField.getText());
        
        if (this.business.getBranches().checkIfBranchExists(branchName))
        {
            JOptionPane.showMessageDialog(null, "Branch already exists. Use a different name #");
        }
        else{
            BranchDirectory branches = this.business.getBranches();                
            branches.createBranch(branchName, libraryBuilding);
            displayBranches();

            branchNameTextField.setText("");
            libBuildingNumTextField.setText("");
        }
    }//GEN-LAST:event_addBranchBtnActionPerformed

    private void deleteBranchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBranchButtonActionPerformed
        int selectedRow = branchesJTable.getSelectedRow();  
        if(selectedRow >= 0) {
            String branchId =  branchesJTable.getValueAt(selectedRow, 0).toString();
            this.business.getBranches().removeBranch(branchId); 
            displayBranches();
        } else {
            
        }
    }//GEN-LAST:event_deleteBranchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBranchBtn;
    private javax.swing.JLabel branchNameLabel;
    private javax.swing.JTextField branchNameTextField;
    private javax.swing.JTable branchesJTable;
    private javax.swing.JLabel buildingNumLabel;
    private javax.swing.JButton deleteBranchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField libBuildingNumTextField;
    // End of variables declaration//GEN-END:variables

    /*private void populateDropdowns() {
        ArrayList<Library> libraries = this.business.getLibraries().getLibraryList();
        
        for(Library l: libraries) {
            libCBox.addItem(Integer.toString(l.getBuildingNumber()));
        }
    }*/
    
}
