/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminPanels;

import Business.Branch;
import Business.Business;
import Business.Library;
import Customer.Employee;
import Customer.EmployeeDirectory;
import Customer.Customer;
import Customer.CustomerDirectory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prasad
 */
public class CustomersAndEmployeesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomersJPanel
     */
    private Business business;
    DefaultTableModel customersTableModel;
    DefaultTableModel EmployeesTableModel;
    
    public CustomersAndEmployeesJPanel(Business business) {
        initComponents();
        
        this.business = business;
        this.customersTableModel = (DefaultTableModel) custJTable.getModel();
        this.EmployeesTableModel = (DefaultTableModel) empJTable.getModel();
        
        displayCustomers();
        populateBranches();
        
        displayEmployees();
    }
    
    public void displayCustomers(){
        ArrayList<Customer> customers = this.business.getCustomersList().getCustomerlist();
        if(customers.size() >= 0) {
            customersTableModel.setRowCount(0);
            for(Customer c: customers) {
                Object row[] = new Object[2];
                row[0] = c.getPersonID();
                row[1] = c.getName();
                customersTableModel.addRow(row);
            }
        }
    }
    
    public void populateBranches()
    {
        ArrayList<Branch> branches = this.business.getBranches().getBranchesList();
        
        for(Branch b: branches) {
            selectBranchCBox.addItem(b.getBranchId());
        }
    }
    
    public void displayEmployees(){
        ArrayList<Employee> employees = this.business.getEmployeesList().getEmployees();
        if(employees.size() >= 0) {
            EmployeesTableModel.setRowCount(0);
            for(Employee e: employees) {
                Object row[] = new Object[5];
                row[0] = e.getPersonID();
                row[1] = e.getName();
                row[2] = e.getDesignation();
                row[3] = e.getYearsOfExperience();
                EmployeesTableModel.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cidLabel = new javax.swing.JLabel();
        cidTextField = new javax.swing.JTextField();
        cNameLabel = new javax.swing.JLabel();
        cnameTextField = new javax.swing.JTextField();
        addCustBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        empIdTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        empNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        empDesignationCbox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        yrsOfExpTextField = new javax.swing.JTextField();
        addEmpBtn = new javax.swing.JButton();
        empBranchLabel = new javax.swing.JLabel();
        selectBranchCBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        custJTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        empJTable = new javax.swing.JTable();

        cidLabel.setText("Customer Id");

        cidTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidTextFieldActionPerformed(evt);
            }
        });

        cNameLabel.setText("Customer Name");

        addCustBtn.setText("Add Customer");
        addCustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Employee Id");

        jLabel2.setText("Employee Name");

        jLabel3.setText("Designation");

        empDesignationCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Librarian", "Branch Manager" }));

        jLabel4.setText("Yrs of Experience");

        addEmpBtn.setText("Add Employee");
        addEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpBtnActionPerformed(evt);
            }
        });

        empBranchLabel.setText("Branch");

        custJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Customer Id", "Customer Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(custJTable);

        empJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "EmpId", "Name", "Designation", "Experience", "Library"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(empJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                        .addComponent(cidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(empBranchLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(empIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(empNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empDesignationCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yrsOfExpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectBranchCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(addEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addCustBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cidLabel)
                            .addComponent(cidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cNameLabel)
                            .addComponent(cnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(addCustBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(empIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(empNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(empDesignationCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(yrsOfExpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empBranchLabel)
                            .addComponent(selectBranchCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(addEmpBtn))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addCustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustBtnActionPerformed
        String customerId = cidTextField.getText();
        String customerName = cnameTextField.getText();
        
        //chec if customer already exists
        
        if (this.business.getCustomersList().checkIfCustomerExists(customerId))
        {
            JOptionPane.showMessageDialog(null, "Customer already exists!");
        }
        else{
        
            CustomerDirectory customers = this.business.getCustomersList();                
            customers.createCustomer(customerId, customerName);
            
            displayCustomers();

            cidTextField.setText("");
            cnameTextField.setText("");
        }
    }//GEN-LAST:event_addCustBtnActionPerformed

    private void cidTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidTextFieldActionPerformed

    private void addEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpBtnActionPerformed
        String employeeId = empIdTextField.getText();
        String employeeName = empNameTextField.getText();
        String empDesignation = empDesignationCbox.getSelectedItem().toString();
        String empExp = yrsOfExpTextField.getText();
        String branchId = selectBranchCBox.getSelectedItem().toString();
        //int libraryBuildingNum = Integer.valueOf(selectBranchCBox.getSelectedItem().toString());
        
        if (this.business.getEmployeesList().checkIfEmployeeExists(employeeId))
        {
            JOptionPane.showMessageDialog(null, "Employee already exists!");
        }
        else{
        
            EmployeeDirectory emps = this.business.getEmployeesList();
            emps.addEmployee(employeeId, employeeName, empDesignation, Float.valueOf(empExp));
            
            //update the library
            
            Branch branch = this.business.getBranches().findBranch(branchId);
            Library lib = branch.getLibrary();
            
            lib.getEmployees().addEmployee(employeeId, employeeName, empDesignation, Float.valueOf(empExp));
            
            displayEmployees();

            empIdTextField.setText("");
            empNameTextField.setText("");
            empDesignationCbox.setSelectedIndex(-1);
            yrsOfExpTextField.setText("");
            selectBranchCBox.setSelectedIndex(-1);    
        }
    }//GEN-LAST:event_addEmpBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustBtn;
    private javax.swing.JButton addEmpBtn;
    private javax.swing.JLabel cNameLabel;
    private javax.swing.JLabel cidLabel;
    private javax.swing.JTextField cidTextField;
    private javax.swing.JTextField cnameTextField;
    private javax.swing.JTable custJTable;
    private javax.swing.JLabel empBranchLabel;
    private javax.swing.JComboBox<String> empDesignationCbox;
    private javax.swing.JTextField empIdTextField;
    private javax.swing.JTable empJTable;
    private javax.swing.JTextField empNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> selectBranchCBox;
    private javax.swing.JTextField yrsOfExpTextField;
    // End of variables declaration//GEN-END:variables
}
