/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminPanels;

import Business.Business;
import Business.Library;
import Business.LibraryDirectory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chilukuri
 */
public class LibraryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LibraryJPanel
     */
    private Business business;
    DefaultTableModel librariesTableModel;
    
    public LibraryJPanel(Business business) {
        initComponents();
        
        this.business = business;
        this.librariesTableModel = (DefaultTableModel) librariesJTable.getModel();
        
        displayLibraries();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buildingNumLabel = new javax.swing.JLabel();
        buildingNumTextField = new javax.swing.JTextField();
        addLibBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        librariesJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setText("Libraries");

        buildingNumLabel.setText("Building #");

        addLibBtn.setText("Add");
        addLibBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLibBtnActionPerformed(evt);
            }
        });

        librariesJTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        librariesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Building #"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(librariesJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(buildingNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)
                            .addComponent(buildingNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(addLibBtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buildingNumLabel)
                            .addComponent(buildingNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(addLibBtn)))
                .addContainerGap(349, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addLibBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLibBtnActionPerformed
        /*int buildingNumber = Integer.parseInt(buildingNumTextField.getText());
        
        if (this.business.getLibraries().checkIfLibraryExists(buildingNumber))
        {
            JOptionPane.showMessageDialog(null, "Library already exists. Use a different building #");
        }
        else{
            LibraryDirectory libs = this.business.getLibraries();                
            libs.createLibrary(buildingNumber);
            displayLibraries();

            buildingNumTextField.setText("");
        }*/
    }//GEN-LAST:event_addLibBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLibBtn;
    private javax.swing.JLabel buildingNumLabel;
    private javax.swing.JTextField buildingNumTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable librariesJTable;
    // End of variables declaration//GEN-END:variables

    private void displayLibraries() {
        /*ArrayList<Library> libraries = this.business.getLibraries().getLibraryList();
        if(libraries.size() >= 0) {
            librariesTableModel.setRowCount(0);
            for(Library l: libraries) {
                Object row[] = new Object[1];
                row[0] = l.getBuildingNumber();
                librariesTableModel.addRow(row);
            }
        }*/
    }
}
